### PR TITLE
[rpm] sample spec file added

### PR DESCRIPTION
**Pull request by CODeRUS**

### CODE REVIEW

**Comment by Kaffeine** [comment]
Hello.

I know nothing about rpm, so I asked @TemeV to review it.

Thank you for the contribution.

**Comment by TemeV** [comment]
The spec file is not working. Running qmake gives me this error:
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.ojcAwF (%build)
    Bad exit status from /var/tmp/rpm-tmp.ojcAwF (%build)
23:42:45: The process "/home/temev/.config/SailfishBeta2/mer-sdk-tools/MerSDK/SailfishOS-armv7hl/qmake" exited with code 1.
Error while building/deploying project telegram-qt (kit: MerSDK-SailfishOS-armv7hl)
When executing step 'qmake'

I couldn't figure out the problem with it.

This seems to create an RPM with the library and the testApp. I'm not sure if this is really relevant, or would it be better to create an RPM for the library only.

**Comment by CODeRUS** [comment]
it not working for qtc, it works only for toolchain build: https://build.merproject.org/package/show/home:coderus:sailfish/telegram-qt

can make changes for making it work under qtc if you really want it.

**Comment by Kaffeine** [comment]
I think it would be much more convenient, if the spec will work with QtC.
And the build result on your link says "sailfish armv8el failed".
By the way, I'll try to improve description, bump version to at least 0.1.0. And the license of the library is LGPLv2 now.

**Comment by CODeRUS** [comment]
uic is broken on this obs, waiting for server upgrade, this is the reason of fail.

**Comment by TemeV** [comment]
I made a new rpm packaging for Sailfish repo, so I guess this PR can be closed.
https://github.com/TemeV/telegram-qt-sailfishos

**Comment by Kaffeine** [comment]
Partially reused in a different form.
Thanks!

**Comment by CODeRUS** [comment]
Lol

**Pull request closed without merging**
