### PR TITLE
New signal to update the messages that have been read from the inbox.

### PR DESCRIPTION
**Pull request by joselitofilho**

### CODE REVIEW

**Comment by Kaffeine** [comment]
There is no legal way to get telegram user id, but there is a signal sentMessageStatusChanged(), which should be used instead.

Can you please share your use case, so we can find a solution to fit it?

I'm not sure, but it seems that we *have* to expose user ids to properly support both types of contacts: known by phone and known by nickname.
IIUC, user id would be kept the same if contact, which was been known only by nickname would be known by phone too. TelegramQt used to expose contacts by phone, which could trigger contact identifier changes in such case.

Currently the main "user" of the library is telepathy-morse project and there is one almost "show-stopper" issue with user and chat ids exposing: chat creation method in telepathy should return the resulted id, which is unknown until network reply.

**Comment by joselitofilho** [comment]
The signal sentMessageDeliveryStatusChanged() don't work for me. I need to know if all messages have been read from a user, this occours when you read messages from a user on another telegram.

So, can I change userId to phone?

**Comment by Kaffeine** [comment]
>The signal sentMessageDeliveryStatusChanged() don't work for me. I need to know if all messages have been read from a user, this occours when you read messages from this same user on another telegram.

You're right. I implemented locally read messages to be marked as read on another telegram, but I never thought about the thing that you need. What do you think if we change sentMessageDeliveryStatusChanged() to more generic messageDeliveryStatusChanged() and use it to inform the application about both in and out message status?

>I'am using userId because the signal whenMessageReceived() message only comes userId.
MainWindow::whenMessageReceived() works with message.peer which is a string. The "peer" can starts either "chat" or "user" with id.
Chat id would be "public id", which is an index of chat, starts with 0 and would be 5 for the sixth user chat.
User id is an actual telegram user id.

I'm very appreciating your development and now I think that I should move "telegram chat id <-> public (TgQt) chat id" conversion to telepathy-morse and made telegram-qt to always work with "native", protocol identifiers.

The API issue is CTelegramCore::createChat() method, which is currently returns "public (TgQt) chat id", but it obviously can't return random telegram chat id, which is get known later from the server respond.

It can take a time to add current telegram-qt telegram chat id layer implementation to telepathy-morse, but I think we can add a telegram-qt branch with "native identifiers" for PolibrasNet for that time.

**Comment by Kaffeine** [comment]
I'm changing TelegramQt API to expose native identifiers and will push initial port tomorrow.

**Comment by joselitofilho** [comment]
Nice!

**Comment by Kaffeine** [comment]
>I believe it is not the best option. For this sentMessageDeliveryStatusChanged() is the status of each specific message. The signal updateReadHistoryInbox() is simply to inform that all messages have been read.
You're right. I got used to the https://core.telegram.org/constructor/updateReadMessages

With TelegramNamespace::Peer I added the subj. signal as messageReadInbox(TelegramNamespace::Peer peer, quint32 messageId);
7f350c4cde8393d3e1d76327258029c599ce2216

>No problem! I would like this.
https://github.com/Kaffeine/telegram-qt/commits/native-ids
I still have to port Chat API.

>How do you know about PolibrasNet? haha.
You leaked the name: https://github.com/joselitofilho/telegram-qt/blob/polibras/testApp/MainWindow.cpp#L75

**Pull request closed without merging**
